[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.17.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the manual redirect as the Next.js plugin handles routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[functions]
  included_files = ["dist/**/*"]
  node_bundler = "esbuild"
